apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
    spec:
      containers:
      - name: teste
        image: adrianoagiljr/teste:{{tag}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teste
spec:
  selector:
    app: teste
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

